version: '3.7'
services:
  mysql:
    container_name: tech_story_mysql
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 33206:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tech_story
  api:
    container_name: tech_story_api_server
    build:
      context: ./api
      target: dev
    volumes:
      - ./api:/go/api
    ports:
      - 8000:8000
    links:
      - mysql
    env_file:
      - api/.env
