// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewStory struct {
	Text    string `json:"text"`
	OwnerID string `json:"ownerId"`
}

type Story struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Owner *User  `json:"owner"`
}

type User struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}
