// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewStory struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type NewUser struct {
	UUID        string  `json:"uuid"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type Story struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	User  *User  `json:"user"`
}

type User struct {
	ID          int     `json:"id"`
	UUID        string  `json:"uuid"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}
